FROM hopsoft/graphite-statsd:latest
MAINTAINER Magnus Larsson <magnus.larsson.ml@gmail.com>
ADD graphite-statsd/conf/graphite/graphTemplates.conf /opt/graphite/conf/graphTemplates.conf
ADD graphite-statsd/conf/graphite/composer_widgets.js /opt/graphite/webapp/content/js/composer_widgets.js
ADD graphite-statsd/conf/statsd/config.js /opt/statsd/config.js