#
# Build image with a command like:
#
#    docker build --tag=elasticsearch-custom elk-config/elasticsearch
#
FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.2
ADD elasticsearch.yml /usr/share/elasticsearch/config/
